### ISSUE TITLE
Missing instruction for deploying app

### ISSUE THREAD

**Issue by ajeetraina** [naanunaane/semanti-search#2]
I don't see detailed instructions on how to install this app. Can you please add it? @naanunaane 

Step 1. Install Python

Step 2. Install Prerequisite modules

```
pip3 install transformers
pip3 install torch
```

Step 3. Execute the script

```
python3 set_model.py
```
```
pip3 install torch       
Collecting torch
  Downloading torch-1.9.0-cp39-none-macosx_10_9_x86_64.whl (127.9 MB)
     |████████████████████████████████| 127.9 MB 167 kB/s 
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/site-packages (from torch) (3.7.4.3)
Installing collected packages: torch
Successfully installed torch-1.9.0
ajeetraina@Ajeets-MacBook-Pro semanti-search % python3 set_model.py
Traceback (most recent call last):
  File "/Users/ajeetraina/projects/semanti-search/set_model.py", line 17, in <module>
    con.modelset('bert-qa', 'TORCH', 'CPU', bert_model)
  File "/usr/local/lib/python3.9/site-packages/redisai/client.py", line 198, in modelset
    res = self.execute_command(*args)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 4, but the maximum supported version for reading is 3. Your PyTorch installation may be too old. (init at ../caffe2/serialize/inline_container.cc:132) frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7eff31aa6aaa in /usr/lib/redis/modules/backends/redisai_torch/lib/libc10.so) frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x2062 (0x7eff24a1eb62 in /usr/lib/redis/modules/backends/redisai_torch/lib/libtorch_cpu.so) frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >) + 0x6d (0x7eff24a1f6ad in /usr/lib/redis/modules/backends/redisai_torch/lib/libtorch_cpu.so) frame #3: <unknown function> + 0x2f3f5df (0x7eff25aa25df in /usr/lib/redis/modules/backends/redisai_torch/lib/libtorch_cpu.so) frame #4: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x67 (0x7eff25aa1ae7 in /usr/lib/redis/modules/backends/redisai_torch/lib/libtorch_cpu.so) frame #5: torch::jit::load(std::istream&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x75 (0x7eff25aa23f5 in /usr/lib/redis/modules/backends/redisai_torch/lib/libtorch_cpu.so) frame #6: torchLoadModel + 0x22e (0x7eff31cdfffe in /usr/lib/redis/modules/backends/redisai_torch/redisai_torch.so) frame #7: RAI_ModelCreateTorch + 0x9a (0x7eff31cd864a in /usr/lib/redis/modules/backends/redisai_torch/redisai_torch.so) frame #8: RAI_ModelCreate + 0x16d (0x7eff86deafcd in /usr/lib/redis/modules/redisai.so) frame #9: RedisAI_ModelSet_RedisCommand + 0x8b6 (0x7eff86de4166 in /usr/lib/redis/modules/redisai.so) frame #10: RedisModuleCommandDispatcher + 0x54 (0x5561e8b91ca4 in redis-server *:6379) frame #11: call + 0x9d (0x5561e8b1df0d in redis-server *:6379) frame #12: processCommand + 0x327 (0x5561e8b1e687 in redis-server *:6379) frame #13: processCommandAndResetClient + 0x10 (0x5561e8b2c280 in redis-server *:6379) frame #14: processInputBuffer + 0x18f (0x5561e8b307cf in redis-server *:6379) frame #15: <unknown function> + 0xd4b4c (0x5561e8badb4c in redis-server *:6379) frame #16: aeProcessEvents + 0x111 (0x5561e8b17a21 in redis-server *:6379) frame #17: aeMain + 0x2b (0x5561e8b17eab in redis-server *:6379) frame #18: main + 0x4db (0x5561e8b147eb in redis-server *:6379) frame #19: __libc_start_main + 0xeb (0x7eff8783009b in /lib/x86_64-linux-gnu/libc.so.6) frame #20: _start + 0x2a (0x5561e8b14a7a in redis-server *:6379) 
```

**Comment by ajeetraina** [comment]
@naanunaane Any comments?

**Comment by rokosbasilisk** [comment]
> @naanunaane Any comments?

will update instructions today.

**Comment by arbdwj** [comment]
> @naanunaane Any comments?

will do by today eod https://github.com/naanunaane/semanti-search/issues/3
